#!/bin/bash

if [ "$#" -ne 2 ] || [ "$1" != "--origin-domain" ]; then
    echo "Usage: $0 --origin-domain domain"
    exit 1
fi

DOMAIN=$2
if [ ! -d "certs" ]; then
    mkdir certs
fi

openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout certs/cdn_key.pem \
    -out certs/cdn_cert.pem \
    -subj "/CN=$DOMAIN" \
    -addext "subjectAltName=DNS:$DOMAIN"
